# Generated by Django 2.2.7 on 2019-11-09 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='is_archive',
            new_name='delete',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_archive',
            new_name='delete',
        ),
    ]
