# Generated by Django 2.2.7 on 2019-11-09 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_app', '0002_auto_20191109_0323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='delete',
            new_name='is_deleted',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='delete',
            new_name='is_deleted',
        ),
    ]
